In [ ]:
import numpy as np
import pandas as pd


In [ ]:
data=pd.read_csv("/iris.data",header=None,usecols=[0,1,2,3])

In [ ]:
data.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [ ]:
data

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [ ]:
norm_data=(data-data.min())/(data.max()-data.min())

In [ ]:
norm_data

0         1         2         3
0    0.222222  0.625000  0.067797  0.041667
1    0.166667  0.416667  0.067797  0.041667
2    0.111111  0.500000  0.050847  0.041667
3    0.083333  0.458333  0.084746  0.041667
4    0.194444  0.666667  0.067797  0.041667
..        ...       ...       ...       ...
145  0.666667  0.416667  0.711864  0.916667
146  0.555556  0.208333  0.677966  0.750000
147  0.611111  0.416667  0.711864  0.791667
148  0.527778  0.583333  0.745763  0.916667
149  0.444444  0.416667  0.694915  0.708333

[150 rows x 4 columns]

In [ ]:
from scipy.spatial.distance import euclidean, pdist, squareform
def similarity_func(u, v):
    return 1/(1+euclidean(u,v))

In [ ]:
dist = pdist(data,similarity_func)

In [ ]:
dist


array([0.64997679, 0.66229466, 0.60676885, ..., 0.6186429 , 0.60963996,
       0.56557421])

In [ ]:
df_elucid = pd.DataFrame(squareform(dist), columns=data.index, index=data.index)

In [ ]:
df_elucid

0         1         2         3         4         5         6    \
0    0.000000  0.649977  0.662295  0.606769  0.876101  0.618643  0.658061   
1    0.649977  0.000000  0.769231  0.750941  0.621784  0.478270  0.662295   
2    0.662295  0.769231  0.000000  0.803246  0.662295  0.479322  0.790779   
3    0.606769  0.750941  0.803246  0.000000  0.606769  0.461640  0.750941   
4    0.876101  0.621784  0.662295  0.606769  0.000000  0.618643  0.685750   
..        ...       ...       ...       ...       ...       ...       ...   
145  0.176865  0.175439  0.170528  0.174049  0.175406  0.189220  0.172507   
146  0.189513  0.190487  0.184143  0.189095  0.187613  0.200452  0.185733   
147  0.183156  0.181855  0.176630  0.180727  0.181671  0.195985  0.178780   
148  0.176966  0.174885  0.170978  0.174852  0.176097  0.189934  0.173921   
149  0.194551  0.194050  0.188721  0.194186  0.193284  0.207539  0.191651   

          7         8         9    ...       140       141       142  \
0    0.852366  0.520304  0.680716  ...  0.166114  0.177405  0.192000   
1    0.702117  0.662295  0.852366  ...  0.164678  0.175373  0.193016   
2    0.708060  0.696432  0.759747  ...  0.160545  0.170408  0.187450   
3    0.666667  0.769231  0.759747  ...  0.163803  0.173604  0.193150   
4    0.817256  0.520304  0.653958  ...  0.164972  0.175866  0.190615   
..        ...       ...       ...  ...       ...       ...       ...   
145  0.178606  0.169083  0.176463  ...  0.702117  0.803246  0.491543   
146  0.192308  0.184181  0.191564  ...  0.484728  0.514563  0.646111   
147  0.185263  0.175406  0.183231  ...  0.621784  0.658061  0.563508   
148  0.178919  0.169815  0.176297  ...  0.615574  0.549893  0.513167   
149  0.197598  0.188597  0.195844  ...  0.471143  0.471143  0.750941   

          143       144       145       146       147       148       149  
0    0.159811  0.162969  0.176865  0.189513  0.183156  0.176966  0.194551  
1    0.158210  0.161116  0.175439  0.190487  0.181855  0.174885  0.194050  
2    0.154431  0.157393  0.170528  0.184143  0.176630  0.170978  0.188721  
3    0.157486  0.160447  0.174049  0.189095  0.180727  0.174852  0.194186  
4    0.158802  0.161996  0.175406  0.187613  0.181671  0.176097  0.193284  
..        ...       ...       ...       ...       ...       ...       ...  
145  0.576420  0.618643  0.000000  0.561474  0.734994  0.598508  0.513167  
146  0.433338  0.437728  0.561474  0.000000  0.631674  0.483627  0.603958  
147  0.542707  0.557499  0.734994  0.631674  0.000000  0.618643  0.609640  
148  0.553641  0.615574  0.598508  0.483627  0.618643  0.000000  0.565574  
149  0.431204  0.443070  0.513167  0.603958  0.609640  0.565574  0.000000  

[150 rows x 150 columns]

In [ ]:
def form_clusters(similarity_matrix):
    m = len(similarity_matrix)
    clusters = []
    for i in range(m):
        average_dissimilarity = sum(similarity_matrix[i]) - similarity_matrix[i][i]
        average_dissimilarity /= m-1
        cluster_i = [i]
        for j in range(m):
            if j != i and similarity_matrix[i][j] < average_dissimilarity:
                cluster_i.append(j)
        clusters.append(cluster_i)
    return clusters

In [ ]:
clusters = form_clusters(df_elucid)

In [ ]:
for i, cluster in enumerate(clusters):
    print(f"Cluster {i+1}: {cluster}")

Cluster 1: [0, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149]
Cluster 2: [1, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149]
Cluster 3: [2, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,

In [ ]:
def is_subset(cluster_a, cluster_b):
    return set(cluster_a).issubset(set(cluster_b))

In [ ]:
def remove_subsets(clusters):
    sorted_clusters = sorted(clusters, key=len, reverse=True)
    non_subset_clusters = []

    for cluster in sorted_clusters:
        is_subset_flag = False
        for non_subset_cluster in non_subset_clusters:
            if is_subset(cluster, non_subset_cluster):
                is_subset_flag = True
                break

        # If the current cluster is not a subset, add it to the final list
        if not is_subset_flag:
            non_subset_clusters.append(cluster)

    return non_subset_clusters

In [ ]:
p_clusters = remove_subsets(clusters)

In [ ]:
for i, cluster in enumerate(p_clusters):
    print(f"Cluster {i+1}: {cluster}")

def calculate_similarity(cluster_a, cluster_b):
    intersection = len(set(cluster_a).intersection(set(cluster_b)))
    union = len(set(cluster_a).union(set(cluster_b)))
    return intersection / union

Cluster 1: [93, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 26, 27, 28, 29, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 54, 56, 58, 65, 70, 72, 75, 76, 77, 83, 86, 100, 101, 102, 103, 104, 105, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 120, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149]
Cluster 2: [57, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 27, 28, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 45, 46, 47, 48, 49, 50, 51, 52, 54, 56, 58, 65, 70, 72, 75, 76, 77, 83, 86, 100, 101, 102, 103, 104, 105, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149]
Cluster 3: [0, 50, 51, 52, 53, 54, 55, 56, 57, 58

In [ ]:
def create_similarity_matrix(clusters):
    p = len(clusters)
    similarity_matrix = np.zeros((p, p))

    for i in range(p):
        for j in range(p):
            similarity_matrix[i, j] = calculate_similarity(clusters[i], clusters[j])

    return similarity_matrix

In [ ]:
similarity_matrix = create_similarity_matrix(p_clusters)

In [ ]:
print("Similarity Matrix :")
print(similarity_matrix)

Similarity Matrix :
[[1.         0.93636364 0.43150685 ... 0.51724138 0.5042735  0.45833333]
 [0.93636364 1.         0.45070423 ... 0.47863248 0.46610169 0.4214876 ]
 [0.43150685 0.45070423 1.         ... 0.12666667 0.12666667 0.12      ]
 ...
 [0.51724138 0.47863248 0.12666667 ... 1.         0.97101449 0.84931507]
 [0.5042735  0.46610169 0.12666667 ... 0.97101449 1.         0.84931507]
 [0.45833333 0.4214876  0.12       ... 0.84931507 0.84931507 1.        ]]


In [ ]:
def merge_clusters(cluster_a, cluster_b):
    return list(set(cluster_a).union(set(cluster_b)))

In [ ]:
def find_most_similar_clusters(similarity_matrix):
    p = similarity_matrix.shape[0]
    max_similarity = 0
    most_similar_clusters = (0, 0)

    for i in range(p):
        for j in range(i + 1, p):
            if similarity_matrix[i, j] > max_similarity:
                max_similarity = similarity_matrix[i, j]
                most_similar_clusters = (i, j)

    return most_similar_clusters




In [ ]:
most_similar_clusters = find_most_similar_clusters(similarity_matrix)
cluster_k, cluster_l = most_similar_clusters

In [ ]:
new_cluster = merge_clusters(p_clusters[cluster_k], p_clusters[cluster_l])

In [ ]:
print(f"Merged Cluster: {new_cluster}")

Merged Cluster: [0, 1, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149]


In [ ]:
desired_num_clusters = 10  # Replace K with your desired number of clusters

while len(p_clusters) > desired_num_clusters:
    # Step 3A: Remove clusters that are subsets of others
    p_clusters = remove_subsets(p_clusters)

    # Step 3B: Create similarity matrix C
    similarity_matrix_C = create_similarity_matrix(p_clusters)

    # Step 3C: Find most similar clusters, merge them, and update p_clusters
    most_similar_clusters = find_most_similar_clusters(similarity_matrix)
    cluster_k, cluster_l = most_similar_clusters

    # Merge the most similar clusters
    new_cluster = merge_clusters(p_clusters[cluster_k], p_clusters[cluster_l])

    # Remove the merged clusters from the list
    p_clusters.pop(cluster_k)
    if cluster_l > cluster_k:
        cluster_l -= 1  # Adjust index after removal of previous cluster
    p_clusters.pop(cluster_l)

    # Add the new merged cluster to the list
    p_clusters.append(new_cluster)


# Print the final merged clusters
for i, cluster in enumerate(p_clusters):
    print(f"Final Cluster {i+1}: {cluster}")

IndexError: ignored